fix(duckdb-driver): use schema param in information_schema queries
cube-js/cube pull request #7355
Opened 2023-10-29 19:19 UTC by MikeNitsenko

There is a change on DuckDB's side, so previously `SET schema=<value>` worked for `information_schema` queries.
Now, we need the combination of `SET` and `WHERE` clause.
- `WHERE` clause will narrow the list of returned schemas
- `SET` will allow using these tables without referencing the catalog to resolve ambiguity.

> There is confusion with the param naming on DuckDB's side. While the param is called `schema` in [docs](https://duckdb.org/docs/archive/0.9.1/sql/configuration), when you issue `SET schema=<value>` it sets the **catalog**.

2023-10-29 19:30 UTC, ovr commented on packages/cubejs-duckdb-driver/src/DuckDBDriver.ts
> +    this.schema = getEnv('duckdbSchema', this.config);
Let's allow the override schema by passing it with config. We use the same approach for all drivers.

2023-10-29 21:39 UTC, ovr approved these changes

2023-10-29 21:54 UTC, ovr requested changes
unit tests failed...

2023-10-30 08:27 UTC, MikeNitsenko commented
> unit tests failed...

@ovr I restarted tests and they passed ok

2023-10-30 08:28 UTC, merged